[profile.default]
src = "src"
out = "out"
libs = ["lib"]
optimizer = true
optimizer_runs = 2000
evm_version = "paris"
# See more config options https://github.com/foundry-rs/foundry/tree/master/config
